### ISSUE TITLE
prog_exec has no way to report a vm error

### ISSUE THREAD

**Issue by jackcmay** [qmonnet/rbpf#37]
Callers may not want to panic if there is a problem running the program and instead may want to exit gracefully and report an error.

Consider changing:
```rust
pub fn prog_exec(&self, mem: &[u8], mbuff: &[u8]) -> u64
```

To:
```rust
pub fn prog_exec(&self, mem: &[u8], mbuff: &[u8]) -> Result<u64, Error>
```

**Comment by jackcmay** [comment]
Can we get this in the same release as the other public interface changes?  Doing so would reduce the change of breaking backward compatibility in the future.

**Comment by qmonnet** [comment]
Sure. I have no constraints regarding the release on my side anyway, so we only tag once you feel everything you need in the release is covered :).

For the record this is the logical continuation of #30.

**Comment by jackcmay** [comment]
FYI, I'm working on this issue

**Comment by jackcmay** [comment]
@qmonnet 

What do you think about returning a `String` instead of `Error`?  Doesn't look like Error is adding anything in this case.  Would also like to convert new, set_verifier, etc... to `String` 

```rust
-> Result<u64, String>
```
instead of
```rust
-> Result<u64, Error>
```

**Comment by qmonnet** [comment]
Well I did the opposite, my first PR would use a `String` for the return values and I converted that to `Error`s based on suggestions I got :). What's the problem with `Error`s? This is something you can propagate and catch more easily than a string I would think?

**Comment by jackcmay** [comment]
I see propagation and catch being handled by normal `Result` handling.  I guess I don't see the advantage of using `Error` in this case since only ErrorKind::Other is used and just used as a wrapper for the string without adding any additional information.  If there was a need to return other types of `ErrorKind` I could see the benefit but otherwise, I must be missing something :-)

**Comment by jackcmay** [comment]
Maybe a better approach would be a module-specific error enum:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=090c45f8c4f4ec5c373a5f2cafdf3817

**Comment by jackcmay** [comment]
@qmonnet I would like to get this issue resolved early this week so we can release.  I can submit my PR with changes to return Result<(), Error> that I have ready or I can rework to include my suggestion to return a string or custom Error enum.  Please let me know, thanks!

**Comment by qmonnet** [comment]
Sorry for the late reply.

My preference would be to keep an `Error` over a `String` at the moment. This being said, I like your suggestion of using a custom Error enum. Just one question, because I didn't have time to sort it out: say we make the verifier return some error from this enum, what would be the return type? Is it something like `Result<(), Error>` still, or rather like `Result<(), EbpfError>` instead? In the latter case, does a custom verifier have a way to add custom error types without touching at the enum? Just to make sure people can return whatever error they want, but since your own verifier probably has new reasons to reject programs I guess you found a way to make it work :).

Please send your PR, either with an `Error` or with the custom `Error` module.

**Comment by jackcmay** [comment]
That's a good question and I've been pondering it

Maybe and enum containing the string portion of the verifier error...

```rust
pub enum EbpfError {
     NoProg,
     VerifierError { err: String },
}
```
